#pragma once
#include <gl/glut.h>

enum TEXTURE
{
	TEXTURE_PLAYER_IDLE,
	TEXTURE_PLAYER_JUMP,
	TEXTURE_PLAYER_RUN_1,
	TEXTURE_PLAYER_RUN_2,
	TEXTURE_KURIBO_RUN,
	TEXTURE_KURIBO_SQUISH,
	TEXTURE_CAKE,
	TEXTURE_COIN_1,
	TEXTURE_FIREWORK_1,
	TEXTURE_FIREWORK_2,
	TEXTURE_FIREWORK_3,
	TEXTURE_GOAL_FLAG,
	TEXTURE_TITLE,
	TEXTURE_BLOCK_COIN_1,
	TEXTURE_BLOCK_COIN_2,
	TEXTURE_BLOCK_COIN_3,
	TEXTURE_BLOCK_COIN_4,
	TEXTURE_PARTS,
	TEXTURE_FIREBALL,
	TEXTURE_LIFT,
	TEXTURE_FONT,
	TEXTURE_SCORE_100,
	TEXTURE_SCORE_200,
	TEXTURE_SCORE_400,
	TEXTURE_SCORE_500,
	TEXTURE_SCORE_800,
	TEXTURE_SCORE_1000,
	TEXTURE_SCORE_2000,
	TEXTURE_SCORE_4000,
	TEXTURE_SCORE_5000,
	TEXTURE_SCORE_8000,
	TEXTURE_KOOPA_IDLE_1,
	TEXTURE_KOOPA_IDLE_2,
	TEXTURE_KOOPA_IDLE_FIRE_1,
	TEXTURE_KOOPA_IDLE_FIRE_2,
	TEXTURE_KOOPA_FIRE_1,
	TEXTURE_KOOPA_FIRE_2,
	TEXTURE_NOKONOKO_RETURN,
	TEXTURE_NOKONOKO_RUN_1,
	TEXTURE_NOKONOKO_RUN_2,
	TEXTURE_NOKONOKO_SQUISH,
	TEXTURE_MAX
};

typedef struct tagRGB {
	unsigned char r;
	unsigned char g;
	unsigned char b;
} RGB;

typedef struct tagTEX {
	char fileName[64];
	RGB colorKey;
} TEX;

class TextureManager
{
	GLuint m_textures[TEXTURE_MAX];

public:
	TextureManager();
	~TextureManager();

	bool init();
	void release();
	void setTexture(enum TEXTURE _texture);
	void setTexture(GLuint _texture);
	GLuint getTexture(enum TEXTURE _texture);

	void unbindTexture();
};

extern TextureManager g_textureManager;

