#pragma once

#include "Rect.h"

enum {
	TEXTURE_BIGMARIO_BRAKE,
	TEXTURE_BIGMARIO_CROUCH,
	TEXTURE_BIGMARIO_DIE,
	TEXTURE_BIGMARIO_FLAGPOLE_1,
	TEXTURE_BIGMARIO_FLAGPOLE_2,
	TEXTURE_BIGMARIO_IDLE,
	TEXTURE_BIGMARIO_JUMP,
	TEXTURE_BIGMARIO_RUN_1,
	TEXTURE_BIGMARIO_RUN_2,
	TEXTURE_BIGMARIO_RUN_3,
	TEXTURE_SMALLMARIO_BRAKE,
	TEXTURE_SMALLMARIO_DIE,
	TEXTURE_SMALLMARIO_FLAGPOLE_1,
	TEXTURE_SMALLMARIO_FLAGPOLE_2,
	TEXTURE_SMALLMARIO_IDLE,
	TEXTURE_SMALLMARIO_JUMP,
	TEXTURE_SMALLMARIO_RUN_1,
	TEXTURE_SMALLMARIO_RUN_2,
	TEXTURE_SMALLMARIO_RUN_3,
	TEXTURE_KURIBO_RUN,
	TEXTURE_KURIBO_SQUISH,
	TEXTURE_NOKONOKO_RUN_1,
	TEXTURE_NOKONOKO_RUN_2,
	TEXTURE_NOKONOKO_SQUISH,
	TEXTURE_NOKONOKO_RETURN,
	TEXTURE_MAX
};

struct Texture {
	const char* m_fileName;
	unsigned int m_texture;
	Rect m_bound;

	int init();
	static int initAll();
};

extern Texture g_textures[TEXTURE_MAX];