#pragma once

#include <vector>

enum {
	ANIMATION_NONE = -1,
	ANIMATION_PLAYER_IDLE,
	ANIMATION_PLAYER_RUN,
	ANIMATION_PLAYER_JUMP,
	ANIMATION_PLAYER_DIE,
	ANIMATION_PLAYER_FLAG_POLE,
	ANIMATION_KOOPA,
	ANIMATION_KOOPA_FIRE,
	ANIMATION_NOKONOKO_RUN,
	ANIMATION_NOKONOKO_SHELL,
	ANIMATION_NOKONOKO_RETURN,
	ANIMATION_RED_NOKONOKO_RUN,
	ANIMATION_RED_NOKONOKO_SHELL,
	ANIMATION_RED_NOKONOKO_RETURN,
	ANIMATION_BLOCK_COIN,
	ANIMATION_FIREWORK,
	ANIMATION_MAX
};

struct Animation {
	std::vector<int> m_keys;
	int m_rate;
	int m_next;

	Animation();
	static int initAll();
};

extern Animation g_animations[ANIMATION_MAX];