#pragma once

#include "score.h"
#include "sound/audio.h"

namespace komm {

	const unsigned int FULL = 192;
	const unsigned int HALF = 96;
	const unsigned int QUARTER = 48;
	const unsigned int EIGHTH = 24;
	const unsigned int SIXTEENTH = 12;


	SCORE pulse0[] = {

		{E,4, EIGHTH + SIXTEENTH}, {E,4,SIXTEENTH + SIXTEENTH}, {E, 4, SIXTEENTH}, {E, 4, EIGHTH}, {E, 4, QUARTER}, {D, 4, QUARTER},
		{C,4,QUARTER}, {C,4,QUARTER}, {E,4,QUARTER}, {E,4,QUARTER},
		{C,4,QUARTER}, {C,4,QUARTER}, {C,4,QUARTER}, {C,4,QUARTER},
		{C,4,QUARTER}, {C,4,QUARTER}, {C,4,QUARTER}, {D,4,QUARTER},

		{E,4, EIGHTH + SIXTEENTH}, {E,4,SIXTEENTH + SIXTEENTH}, {E, 4, SIXTEENTH}, {E, 4, EIGHTH}, {E, 4, QUARTER}, {D, 4, QUARTER},
		{C,4,QUARTER}, {C,4,QUARTER}, {E,4,QUARTER}, {E,4,QUARTER},
		{C,4,QUARTER}, {C,4,QUARTER}, {C,4,QUARTER}, {C,4,QUARTER},
		{C,4,QUARTER}, {C,4,QUARTER}, {C,4,QUARTER}, {REST,9,EIGHTH}, {C,4,EIGHTH},
		
		/* A */
		{E,4,QUARTER}, {REST,9,EIGHTH + SIXTEENTH}, {C,4,SIXTEENTH}, {E,4,EIGHTH}, {F,4,EIGHTH}, {E,4,EIGHTH}, {D,4,SIXTEENTH},{C,4,SIXTEENTH + QUARTER},
		{REST,9,EIGHTH}, {C,5,EIGHTH}, {B,4,EIGHTH}, {C,5,SIXTEENTH}, {B,4,SIXTEENTH + SIXTEENTH}, {G,4,SIXTEENTH}, {E,4,EIGHTH},
		{A,4,QUARTER}, {REST,9,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {C,4,EIGHTH},
		{F,4,EIGHTH}, {E,4,SIXTEENTH}, {F,4,SIXTEENTH + SIXTEENTH}, {G,4,EIGHTH + SIXTEENTH}, {D,4,QUARTER}, {REST,9,EIGHTH}, {C,4,SIXTEENTH},
		
		{E,4,SIXTEENTH + QUARTER},  {REST,9,EIGHTH + SIXTEENTH}, {E,4,SIXTEENTH}, {E,4,EIGHTH}, {F,4,SIXTEENTH}, {E,4,SIXTEENTH + SIXTEENTH}, {D,4,EIGHTH},
		{C,4,SIXTEENTH + QUARTER}, {REST,9,EIGHTH}, {C,5,EIGHTH}, {B,4,EIGHTH}, {C,5,SIXTEENTH}, {B,4,SIXTEENTH + SIXTEENTH}, {G,4,SIXTEENTH}, {E,4,EIGHTH},
		{A,4,QUARTER}, {REST,9,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {C,4,EIGHTH},
		{F,4,EIGHTH}, {E,4,EIGHTH}, {C,4,SIXTEENTH}, {D,4,EIGHTH}, {C,4,SIXTEENTH + QUARTER}, {REST,9,QUARTER},

		/* B */
		{REST,9,QUARTER}, {E,4,EIGHTH}, {E,4,SIXTEENTH}, {F,4,SIXTEENTH + SIXTEENTH}, {E,4,EIGHTH + SIXTEENTH}, {D,4,EIGHTH}, {E,4,SIXTEENTH},
		{F,4,SIXTEENTH + EIGHTH}, {REST,9,EIGHTH}, {C,5,EIGHTH}, {C,5,SIXTEENTH}, {D,5,SIXTEENTH + SIXTEENTH}, {C,5,EIGHTH + SIXTEENTH}, {B,4,SIXTEENTH}, {C,5,EIGHTH},
		{G,4,SIXTEENTH + QUARTER}, {REST,9,EIGHTH}, {G,4,EIGHTH}, {F_SHARP,4,EIGHTH}, {C,5,SIXTEENTH}, {C,5,SIXTEENTH + EIGHTH}, {B,4,EIGHTH},
		{G,4,QUARTER}, {F,4,QUARTER}, {E,4,QUARTER}, {D,4,QUARTER},
		
		{REST,9,EIGHTH}, {E,4,EIGHTH}, {E,4,SIXTEENTH}, {E,4,EIGHTH}, {F,4,SIXTEENTH + SIXTEENTH}, {E,4,EIGHTH + SIXTEENTH}, {D,4,EIGHTH}, {E,4,SIXTEENTH},
		{F,4,SIXTEENTH + EIGHTH}, {REST,9,SIXTEENTH}, {C,4,SIXTEENTH}, {C,5,EIGHTH}, {C,5,SIXTEENTH}, {D,5,SIXTEENTH + SIXTEENTH}, {C,5,EIGHTH + SIXTEENTH}, {B,4,SIXTEENTH}, {C,5,EIGHTH},
		{C,5,SIXTEENTH + QUARTER}, {REST,9,SIXTEENTH}, {G,4,SIXTEENTH}, {C,5,SIXTEENTH}, {D,5,SIXTEENTH}, {F,5,SIXTEENTH}, {E,5,EIGHTH}, {D,5,SIXTEENTH + EIGHTH},{C,5,EIGHTH},
		{C,5,QUARTER}, {B,4,QUARTER}, {C,5,QUARTER},
		{D,5,QUARTER + QUARTER}, {REST,9,QUARTER}, {REST,9,QUARTER}, {REST,9,EIGHTH}, {C,4,EIGHTH},

		/* A */
		{E,4,QUARTER}, {REST,9,EIGHTH + SIXTEENTH}, {C,4,SIXTEENTH}, {E,4,EIGHTH}, {F,4,EIGHTH}, {E,4,EIGHTH}, {D,4,SIXTEENTH},{C,4,SIXTEENTH + QUARTER},
		{REST,9,EIGHTH}, {C,5,EIGHTH}, {B,4,EIGHTH}, {C,5,SIXTEENTH}, {B,4,SIXTEENTH + SIXTEENTH}, {G,4,SIXTEENTH}, {E,4,EIGHTH},
		{A,4,QUARTER}, {REST,9,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {C,4,EIGHTH},
		{F,4,EIGHTH}, {E,4,SIXTEENTH}, {F,4,SIXTEENTH + SIXTEENTH}, {G,4,EIGHTH + SIXTEENTH}, {D,4,QUARTER}, {REST,9,EIGHTH}, {C,4,SIXTEENTH},
		
		{E,4,SIXTEENTH + QUARTER},  {REST,9,EIGHTH + SIXTEENTH}, {E,4,SIXTEENTH}, {E,4,EIGHTH}, {F,4,SIXTEENTH}, {E,4,SIXTEENTH + SIXTEENTH}, {D,4,EIGHTH},
		{C,4,SIXTEENTH + QUARTER}, {REST,9,EIGHTH}, {C,5,EIGHTH}, {B,4,EIGHTH}, {C,5,SIXTEENTH}, {B,4,SIXTEENTH + SIXTEENTH}, {G,4,SIXTEENTH}, {E,4,EIGHTH},
		{A,4,QUARTER}, {REST,9,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {C,4,EIGHTH},

		{F,4,EIGHTH}, {E,4,EIGHTH}, {C,4,SIXTEENTH}, {D,4,EIGHTH}, {C,4,SIXTEENTH + QUARTER}, {REST,9,QUARTER},
		/* C */
		{D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH},
		{E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH},
		{D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH}, {D,4,EIGHTH},
		{E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {E,4,EIGHTH}, {C,4,EIGHTH},
		
		{C,5,QUARTER}, {REST,9,EIGHTH}, {A_SHARP,4,SIXTEENTH}, {A,4,SIXTEENTH}, {G,4,QUARTER}, {REST,9,EIGHTH}, {F,4,EIGHTH},
		{E,4,EIGHTH + SIXTEENTH}, {G,4,SIXTEENTH + QUARTER}, {REST,9,EIGHTH}, {G,4,EIGHTH}, {D,5,EIGHTH}, {C,5,EIGHTH},
		{F,5,SIXTEENTH}, {E,5,SIXTEENTH}, {F,5,EIGHTH}, {E,5,EIGHTH}, {E,5,SIXTEENTH}, {D,5,SIXTEENTH}, {E,5,EIGHTH}, {D,5,EIGHTH}, {D,5,SIXTEENTH}, {C,5,SIXTEENTH}, {D,5,EIGHTH},
		{C,5,EIGHTH + SIXTEENTH}, {G,4,SIXTEENTH + QUARTER}, {REST,9,QUARTER}, {REST,9,EIGHTH}, {C,4,EIGHTH},
		
		{C,5,QUARTER}, {REST,9,EIGHTH}, {A_SHARP,4,SIXTEENTH}, {A,4,SIXTEENTH}, {G,4,QUARTER}, {REST,9,EIGHTH}, {F,4,EIGHTH},
		{E,4,EIGHTH + SIXTEENTH}, {G,4,SIXTEENTH + QUARTER}, {REST,9,EIGHTH}, {G,4,EIGHTH}, {D,5,EIGHTH}, {C,5,EIGHTH},
		{F,5,SIXTEENTH}, {E,5,SIXTEENTH}, {F,5,EIGHTH}, {E,5,EIGHTH}, {E,5,SIXTEENTH}, {D,5,SIXTEENTH}, {E,5,EIGHTH}, {D,5,EIGHTH}, {D,5,SIXTEENTH}, {C,5,SIXTEENTH}, {D,5,EIGHTH},
		{C,5,QUARTER}, {REST,9,QUARTER + HALF},
		
		/* E */
		{F,4,EIGHTH}, {F,4,SIXTEENTH}, {F,4,SIXTEENTH + SIXTEENTH}, {G,4,SIXTEENTH}, {F,4,EIGHTH + EIGHTH}, {REST,9,SIXTEENTH}, {F,4,SIXTEENTH}, {A,4,SIXTEENTH}, {G,4,SIXTEENTH}, {F,4,SIXTEENTH}, {E,4,SIXTEENTH},
		{F,4,EIGHTH}, {F,4,SIXTEENTH}, {F,4,SIXTEENTH + SIXTEENTH},{G,4,SIXTEENTH}, {F,4,EIGHTH + EIGHTH}, {REST,9,EIGHTH}, {D,4,EIGHTH}, {E,4,EIGHTH},
		{F,4,QUARTER + EIGHTH}, {E,4,SIXTEENTH}, {D,4,SIXTEENTH + QUARTER}, {REST,9,QUARTER},
		{A,4,QUARTER + EIGHTH}, {G,4,SIXTEENTH}, {F,4,SIXTEENTH + QUARTER}, {REST,9,QUARTER},

		{A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH},
		{A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {A_SHARP,4,EIGHTH},
		{B,4,HALF + HALF}, {REST,9,QUARTER + EIGHTH}, {C,4,EIGHTH},

		/* A */
		{E,4,QUARTER}, {REST,9,EIGHTH + SIXTEENTH}, {C,4,SIXTEENTH}, {E,4,EIGHTH}, {F,4,EIGHTH}, {E,4,EIGHTH}, {D,4,SIXTEENTH},{C,4,SIXTEENTH + QUARTER},
		{REST,9,EIGHTH}, {C,5,EIGHTH}, {B,4,EIGHTH}, {C,5,SIXTEENTH}, {B,4,SIXTEENTH + SIXTEENTH}, {G,4,SIXTEENTH}, {E,4,EIGHTH},
		{A,4,QUARTER}, {REST,9,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {C,4,EIGHTH},
		{F,4,EIGHTH}, {E,4,SIXTEENTH}, {F,4,SIXTEENTH + SIXTEENTH}, {G,4,EIGHTH + SIXTEENTH}, {D,4,QUARTER}, {REST,9,EIGHTH}, {C,4,SIXTEENTH},

		{E,4,SIXTEENTH + QUARTER},  {REST,9,EIGHTH + SIXTEENTH}, {E,4,SIXTEENTH}, {E,4,EIGHTH}, {F,4,SIXTEENTH}, {E,4,SIXTEENTH + SIXTEENTH}, {D,4,EIGHTH},
		{C,4,SIXTEENTH + QUARTER}, {REST,9,EIGHTH}, {C,5,EIGHTH}, {B,4,EIGHTH}, {C,5,SIXTEENTH}, {B,4,SIXTEENTH + SIXTEENTH}, {G,4,SIXTEENTH}, {E,4,EIGHTH},
		{A,4,QUARTER}, {REST,9,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {A,4,EIGHTH}, {G,4,EIGHTH}, {C,4,EIGHTH},
		{F,4,EIGHTH}, {E,4,EIGHTH}, {C,4,SIXTEENTH}, {D,4,EIGHTH}, {C,4,SIXTEENTH + QUARTER}, {REST,9,QUARTER},
	};

	SCORE triangle[] = {

		{C,3,QUARTER + EIGHTH}, {C,3,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{A,2,QUARTER + EIGHTH}, {A,2,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{F,2,QUARTER + EIGHTH}, {F,2,EIGHTH}, {E,2,QUARTER + EIGHTH}, {E,2,EIGHTH},
		{D,2,QUARTER + EIGHTH}, {D,2,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},

		{C,3,QUARTER + EIGHTH}, {C,3,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{A,2,QUARTER + EIGHTH}, {A,2,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{F,2,QUARTER + EIGHTH}, {F,2,EIGHTH}, {E,2,QUARTER + EIGHTH}, {E,2,EIGHTH},
		{D,2,QUARTER}, {G,2,QUARTER}, {C,3,HALF},

		/* A */
		{C,3,QUARTER}, {C,3,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{A,2,QUARTER}, {A,2,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{F,2,QUARTER}, {F,2,QUARTER}, {E,2,QUARTER}, {E,3,QUARTER},
		{D,2,QUARTER}, {D,2,QUARTER},  {G,2,QUARTER}, {G,3,QUARTER},

		{C,3,QUARTER}, {C,3,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{A,2,QUARTER}, {A,2,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{F,2,QUARTER}, {F,2,QUARTER}, {E,2,QUARTER}, {E,3,QUARTER},
		{D,2,QUARTER}, {G,2,QUARTER}, {C,3,HALF},

		/* B */
		{C,3,QUARTER}, {C,3,QUARTER}, {A_SHARP,2,QUARTER}, {A_SHARP,2,QUARTER},
		{A,2,QUARTER}, {A,2,QUARTER}, {G_SHARP,2,QUARTER}, {G_SHARP,2,QUARTER},
		{G,2,QUARTER}, {G,2,QUARTER}, {F_SHARP,2,QUARTER}, {F_SHARP,2,QUARTER},
		{F,2,QUARTER}, {F,2,QUARTER}, {D,3,QUARTER}, {D,3,QUARTER},

		{C,3,QUARTER}, {C,3,QUARTER}, {A_SHARP,2,QUARTER}, {A_SHARP,2,QUARTER},
		{A,2,QUARTER}, {A,2,QUARTER}, {G_SHARP,2,QUARTER}, {G_SHARP,2,QUARTER},
		{G,2,QUARTER}, {G,2,QUARTER}, {F_SHARP,2,QUARTER}, {F_SHARP,2,QUARTER},
		{G,2,QUARTER}, {G,2,QUARTER}, {G,2,HALF + QUARTER},
		{F,3,QUARTER}, {E,3,QUARTER}, {D,3,QUARTER},

		/* A */
		{C,3,QUARTER}, {C,3,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{A,2,QUARTER}, {A,2,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{F,2,QUARTER}, {F,2,QUARTER}, {E,2,QUARTER}, {E,3,QUARTER},
		{D,2,QUARTER}, {D,2,QUARTER},  {G,2,QUARTER}, {G,3,QUARTER},

		{C,3,QUARTER}, {C,3,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{A,2,QUARTER}, {A,2,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{F,2,QUARTER}, {F,2,QUARTER}, {E,2,QUARTER}, {E,3,QUARTER},

		{D,2,QUARTER}, {G,2,QUARTER}, {C,3,QUARTER}, {REST,9,QUARTER},
		/* C */
		{G,2,QUARTER + EIGHTH}, {G,2,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{C,3,QUARTER + EIGHTH}, {C,3,EIGHTH}, {C,3,QUARTER + EIGHTH}, {C,3,EIGHTH},
		{G,2,QUARTER + EIGHTH}, {G,2,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{C,3,QUARTER + EIGHTH}, {C,3,EIGHTH}, {C,3,QUARTER + EIGHTH}, {C,3,EIGHTH},
		
		{G,2,QUARTER + EIGHTH}, {G,2,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{C,3,QUARTER + EIGHTH}, {C,3,EIGHTH}, {C,3,QUARTER + EIGHTH}, {C,3,EIGHTH},
		{G,2,QUARTER + EIGHTH}, {G,2,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{C,3,QUARTER + EIGHTH}, {C,3,EIGHTH}, {C,3,QUARTER + EIGHTH}, {C,3,EIGHTH},
		
		{G,2,QUARTER + EIGHTH}, {G,2,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{C,3,QUARTER + EIGHTH}, {C,3,EIGHTH}, {C,3,QUARTER + EIGHTH}, {C,3,EIGHTH},
		{G,2,QUARTER + EIGHTH}, {G,2,EIGHTH}, {G,2,QUARTER + EIGHTH}, {G,2,EIGHTH},
		{C,3,QUARTER + EIGHTH}, {C,3,EIGHTH}, {C,3,QUARTER + EIGHTH}, {C,3,EIGHTH},
	
		/* E */
		{D,3,QUARTER}, {D,3,QUARTER}, {C_SHARP,3,QUARTER}, {C_SHARP,3,QUARTER},
		{C,3,QUARTER}, {C,3,QUARTER}, {B,2,QUARTER}, {B,2,QUARTER},
		{A_SHARP,2,QUARTER}, {A_SHARP,2,QUARTER}, {A_SHARP,2,QUARTER}, {A_SHARP,2,QUARTER},
		{G,2,QUARTER}, {G,2,QUARTER}, {G,2,QUARTER}, {G,2,QUARTER},

		{G,2,QUARTER}, {G,2,QUARTER}, {G,2,QUARTER}, {G,2,QUARTER},
		{G,2,EIGHTH},{G,2,EIGHTH},{G,2,EIGHTH},{G,2,EIGHTH},{G,2,EIGHTH},{G,2,EIGHTH},{G,2,EIGHTH},{G,2,EIGHTH},
		{G,2,EIGHTH},{G,2,EIGHTH},{G,2,EIGHTH},{G,2,EIGHTH},{G,2,HALF},

		/* A */
		{C,3,QUARTER}, {C,3,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{A,2,QUARTER}, {A,2,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{F,2,QUARTER}, {F,2,QUARTER}, {E,2,QUARTER}, {E,3,QUARTER},
		{D,2,QUARTER}, {D,2,QUARTER},  {G,2,QUARTER}, {G,3,QUARTER},

		{C,3,QUARTER}, {C,3,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{A,2,QUARTER}, {A,2,QUARTER}, {G,2,QUARTER}, {G,3,QUARTER},
		{F,2,QUARTER}, {F,2,QUARTER}, {E,2,QUARTER}, {E,3,QUARTER},
		{D,2,QUARTER}, {G,2,QUARTER}, {C,3,HALF},
	};

	int PULSE0_COUNT = _countof(pulse0);
	int TRIANGLE_COUNT = _countof(triangle);
}